let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Casual Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-1.jpg",
    
  },
  {
    id: "ioytrhndcv",
    name: "Office Shirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "T Shirt",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p1.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-4.jpg",
  },
  {
    id: "jfhgbvnscssd",
    name: "T Shirt",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p2.jpg",
  },
  {
    id: "jfhgbcssd",
    name: "Fashion men",
    price: 270,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p3.jpg",
  },
  {
    id: "jfhgbvnsdsd",
    name: "Mens suit",
    price: 320,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p4.jpg",
  },
  {
    id: "jfvnscssd",
    name: "Fashion",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p5.jpg",
  },
  {
    id: "jfhgbvnscstrsd",
    name: "Fashion",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p6.jpg",
  },
  {
    id: "jfhgbvnhjk",
    name: "T Shirt",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p7.jpg",
  },
  {
    id: "jfhgasdafsd",
    name: "Fashion",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p8.jpg",
  },
  {
    id: "jfhfdfsd",
    name: "T Shirt",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p9.jpg",
  },
  {
    id: "jfhgbvnscspipsd",
    name: "Mens suit",
    price: 225,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p10.jpg",
  },
  {
    id: "jfhdsfscssd",
    name: "T Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p11.jpg",
  },
  {
    id: "jfhgbvsfgdfgnscssd",
    name: "Fashion men",
    price: 165,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p12.jpg",
  },
  {
    id: "jfhgbvngvfd",
    name: "Mens suit",
    price: 320,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p13.jpg",
  },
  {
    id: "jfhgbvnscsadsfsd",
    name: "Mens suit",
    price: 95,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p14.jpg",
  },
  {
    id: "hjfdgbvnscssd",
    name: "Mens suit",
    price: 145,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p15.jpg",
  },
  {
    id: "jfhgbvnscssdfgdvd",
    name: "Fashion",
    price: 75,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p16.jpg",
  },
  {
    id: "jfhgbvnscssljhjd",
    name: "T Shirt",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/p17.jpg",
  },
 
];
